from setuptools import setup, find_packages

setup(name='compatibleclfcbf',
      version='1.0.0',
      description='Safety-critical control based on CLF and CBFs',
      url='https://github.com/CaipirUltron/CompatibleCLFCBF',
      author='Matheus Reis',
      license='GPLv3',
      packages=find_packages(),
      zip_safe=False,
      install_requires=['numpy',
                        'scipy',
                        'numpy-quaternion', 
                        'sympy', 
                        'quadprog', 
                        'matplotlib', 
                        'qpsolvers', 
                        'picos', 
                        'cvxpy', 
                        'shapely', 
                        'control' ])